CREATE EXTENSION pg_trgm;

SET TIME ZONE 'UTC';

CREATE TABLE reminders (
	id SERIAL PRIMARY KEY,
	user_id TEXT NOT NULL,
	guild_id TEXT NOT NULL,
	channel_id TEXT NOT NULL,
	message_id TEXT NOT NULL,
	message TEXT NOT NULL,
	created TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
	expires TIMESTAMP WITHOUT TIME ZONE NOT NULL
);

CREATE INDEX idx_reminders_expires ON reminders USING BTREE (expires ASC);
