version: '3.9'

x-logging: &logging
  logging:
    options:
      max-file: '1'
      max-size: '5m'

x-restart-policy: &restart_policy
  restart: unless-stopped

services:
  postgres:
    <<: *logging
    <<: *restart_policy
    container_name: postgres
    build: ./postgresql
    environment:
      - POSTGRES_USER=expectopatronum
      - POSTGRES_PASSWORD=expectopatronum
      - POSTGRES_DB=expectopatronum
    ports:
    - '5432:5432'
    volumes:
      - expecto_patronum:/var/lib/postgresql/data
    networks:
      - expecto_patronum

  redis:
    <<: *logging
    <<: *restart_policy
    image: 'redis:7.4.1-alpine'
    container_name: redis
    ports:
    - '6379:6379'
    networks:
      - expecto_patronum

  bot:
    <<: *logging
    <<: *restart_policy
    image: ghcr.io/r-priyam/expecto-patronum:latest
    container_name: expecto_patronum
    build:
      context: ../
    env_file:
      - ../.env
    networks:
      - expecto_patronum
    depends_on:
      - postgres
      - redis
    tty: true

volumes:
  expecto_patronum:

networks:
  expecto_patronum:
