version: '3.9'

x-restart-policy: &restart_policy
  restart: unless-stopped

services:
  postgres:
    <<: *restart_policy
    image: postgres:14-alpine
    container_name: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=expecto_patronum
      - POSTGRES_PASSWORD=expecto_patronum
      - POSTGRES_DB=expecto_patronum
    ports:
      - '5432:5432'
    volumes:
      - expecto_patronum:/var/lib/postgresql/data
    logging:
      options:
        max-size: '5m'
        max-file: '3'
    networks:
      - expecto_patronum

  redis:
    <<: *restart_policy
    image: 'redis:6.2.6-alpine'
    container_name: redis
    command: 'redis-server --requirepass redis'
    ports:
      - '127.0.0.1:6379:6379'
    logging:
      options:
        max-size: '5m'
        max-file: '1'
    networks:
      - expecto_patronum

  bot:
    <<: *restart_policy
    build:
      context: ../
    image: ghcr.io/r-priyam/expecto-patronum:latest
    container_name: expecto_patronum
    env_file:
      - ../.env
    logging:
      options:
        max-size: '10m'
        max-file: '5'
    networks:
      - expecto_patronum
    depends_on:
      - postgres

volumes:
  expecto_patronum:

networks:
  expecto_patronum:
